# Window Manager
<WindowManager>:
    first: first
    second: second
    third: third
    coor: coor
    dist: dist
    cheng1: cheng1
    cheng2: cheng2
    FirstWindow:
        id: first
    SecondWindow:
        id: second
    ThirdWindow:
        id: third
    CoordonneeWindow:
        id: coor
    DistanceWindow:
        id: dist
    ChengWindow1:
        id: cheng1
    ChengWindow2:
        id: cheng2
